// Admin-related action types
export const UPDATE_ROLE_REQUEST = 'UPDATE_ROLE_REQUEST';
export const UPDATE_ROLE_SUCCESS = 'UPDATE_ROLE_SUCCESS';
export const UPDATE_ROLE_FAILED = 'UPDATE_ROLE_FAILED';

export const IS_DELETED_USER_REQUEST = 'IS_DELETED_USER_REQUEST';
export const IS_DELETED_USER_SUCCESS = 'IS_DELETED_USER_SUCCESS';
export const IS_DELETED_USER_FAILED = 'IS_DELETED_USER_FAILED';

export const GET_ALL_USER_REQUEST = 'GET_ALL_USER_REQUEST';
export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS';
export const GET_ALL_USER_FAILED = 'GET_ALL_USER_FAILED';

export const IS_DELETED_STATION_REQUEST = 'IS_DELETED_STATION_REQUEST';
export const IS_DELETED_STATION_SUCCESS = 'IS_DELETED_STATION_SUCCESS';
export const IS_DELETED_STATION_FAILED = 'IS_DELETED_STATION_FAILED';

export const IS_UPDATED_STATION_REQUEST = 'IS_UPDATED_STATION_REQUEST';
export const IS_UPDATED_STATION_SUCCESS = 'IS_UPDATED_STATION_SUCCESS';
export const IS_UPDATED_STATION_FAILED = 'IS_UPDATED_STATION_FAILED';

export const IS_CREATED_STATION_REQUEST = 'IS_CREATED_STATION_REQUEST';
export const IS_CREATED_STATION_SUCCESS = 'IS_CREATED_STATION_SUCCESS';
export const IS_CREATED_STATION_FAILED = 'IS_CREATED_STATION_FAILED';
export const CLEAR = "CLEAR";
