// Train-related action types
export const GET_SHORTEST_PATH_REQUEST = 'GET_SHORTEST_PATH_REQUEST';
export const GET_SHORTEST_PATH_SUCCESS = 'GET_SHORTEST_PATH_SUCCESS';
export const GET_SHORTEST_PATH_FAILED = 'GET_SHORTEST_PATH_FAILED';
export const CLEAR_GET_SHORTEST_PATH = "CLEAR_GET_SHORTEST_PATH";

export const GET_STATION_REQUEST = 'GET_STATION_REQUEST';
export const GET_STATION_SUCCESS = 'GET_STATION_SUCCESS';
export const GET_STATION_FAILED = 'GET_STATION_FAILED';

export const GET_ALL_STATION_REQUEST = 'GET_ALL_STATION_REQUEST';
export const GET_ALL_STATION_SUCCESS = 'GET_ALL_STATION_SUCCESS';
export const GET_ALL_STATION_FAILED = 'GET_ALL_STATION_FAILED';

export const GET_LRU_TRAINS_REQUEST = 'GET_LRU_TRAINS_REQUEST';
export const GET_LRU_TRAINS_SUCCESS = 'GET_LRU_TRAINS_SUCCESS';
export const GET_LRU_TRAINS_FAILED = 'GET_LRU_TRAINS_FAILED';

export const SET_LRU_TRAINS_REQUEST = 'SET_LRU_TRAINS_REQUEST';
export const SET_LRU_TRAINS_SUCCESS = 'SET_LRU_TRAINS_SUCCESS';
export const SET_LRU_TRAINS_FAILED = 'SET_LRU_TRAINS_FAILED';


export const GET_TRAIN_STATUS_REQUEST = 'GET_TRAIN_STATUS_REQUEST';
export const GET_TRAIN_STATUS_SUCCESS = 'GET_TRAIN_STATUS_SUCCESS';
export const GET_TRAIN_STATUS_FAILED = 'GET_TRAIN_STATUS_FAILED';

export const GET_ALL_AVAILABLE_TRAINS_REQUEST = 'GET_ALL_AVAILABLE_TRAINS_REQUEST';
export const GET_ALL_AVAILABLE_TRAINS_SUCCESS = 'GET_ALL_AVAILABLE_TRAINS_SUCCESS';
export const GET_ALL_AVAILABLE_TRAINS_FAILED = 'GET_ALL_AVAILABLE_TRAINS_FAILED';

